### ISSUE TITLE
1.14.4-1.0.0.19 - Crash on server startup.

### ISSUE THREAD

**Issue by MisterShawn** [thraaawn/libnonymous#1]
https://hastebin.com/lapiwomosa.rb

**Comment by davenonymous** [comment]
Thanks for the report. Sorry for the oversight, that's totally on me for not testing servers one last time.
Will be fixed in the next release later today.

**Comment by davenonymous** [comment]
It seems that wasn't enough. Another fix incoming.

**Comment by davenonymous** [comment]
This seems to be resolved. Others successfully run this on servers with these recent fixes.

**Comment by MisterShawn** [comment]
Yes, sorry for not updating. I've been running it fine since your last update. Thank you!
