### ISSUE TITLE
Crash on Server Startup

### ISSUE THREAD

**Issue by Mad-Gnome** [thraaawn/libnonymous#10]
Version: 2.0.4

Forge: 1.18.1-39.0.79 and 1.18.1-39.0.88

https://pastebin.com/ZqHS8F1e
https://pastebin.com/LvTk0bSE

	Mod File: libnonymous-2.0.4.jar
	Failure message: libnonymous (libnonymous) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 2.0.4
	Mod Issue URL: https://github.com/thraaawn/libnonymous/issues
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[fmlloader-1.18.1-39.0.88.jar%2323!/:1.0]

**Comment by davenonymous** [comment]
Oh damn. Sorry. Fixing it now.
