### ISSUE TITLE
no text

### ISSUE THREAD

**Issue by LoganDark** [thraaawn/libnonymous#4]
![image](https://user-images.githubusercontent.com/4723091/79829151-356dc080-8357-11ea-83ed-c7db8ad7ece2.png)
![image](https://user-images.githubusercontent.com/4723091/79829171-3e5e9200-8357-11ea-85cd-8a7c2c25be18.png)

MC 1.15.2, forge 31.1.46, macOS 10.14.6

**Comment by davenonymous** [comment]
> macOS 10.14.6

This. Not sure what's wrong exactly, but macOS does not like my text rendering.

**Comment by LoganDark** [comment]
> macOS does not like my text rendering.

Not everything (or everybody) does. You should provide an option to disable it. :P

Alternatively I'll take a quick look through your code and see if I can spot anything.

**Comment by LoganDark** [comment]
Yeah I couldn't spot anything, mainly because I spent 15 minutes looking for what rendered the text and I couldn't find it. It's so well hidden away and so is the code that actually calls any of those text rendering functions. I'm sure it's very obviously somewhere, but I couldn't find it 😓 only calls to MC's font renderer.
